version: '3.8'

services:
  api-resto:
    container_name: nodejs_sqlite_app
    
    build: .
    
    ports:
      - "80:3000"
      
    volumes:
      - ./data:/app/data

    env_file:
      - .env
      
    restart: unless-stopped